<?php 

    // Let CoreProtector fight with all bad monkeys out there while you drink your tea
    require_once(__DIR__  . '/../../../CoreProtector.php');

    $title       = __( 'Privacy Settings' );
    $parent_file = 'settings/index.php';
?>

<div class="wrap">
  <h1><?php echo $title; ?></h1>
  
  <?php settings_errors(); ?>

  <?php
  
  $action = $this->action_handler();
  $privacy_policy_page_id = (int) get_option( 'wp_page_for_privacy_policy' );


  if ( $this->privacy_policy_page_exists ) {
    $edit_href = add_query_arg(
      array(
        'post'   => $privacy_policy_page_id,
        'action' => 'edit',
      ),
      admin_url( 'post.php' )
    );

    $view_href = get_permalink( $privacy_policy_page_id );

    ?>

    <p class="tools-privacy-edit"><strong>
      <?php
      if ( 'publish' === get_post_status( $privacy_policy_page_id ) ) {
        printf(
          /* translators: 1: URL to edit Privacy Policy page, 2: URL to view Privacy Policy page. */
          __( '<a href="%1$s">Edit</a> or <a href="%2$s">view</a> your Privacy Policy page content.' ),
          esc_url( $edit_href ),
          esc_url( $view_href )
        );
      } else {
        printf(
          /* translators: 1: URL to edit Privacy Policy page, 2: URL to preview Privacy Policy page. */
          __( '<a href="%1$s">Edit</a> or <a href="%2$s">preview</a> your Privacy Policy page content.' ),
          esc_url( $edit_href ),
          esc_url( $view_href )
        );
      }
      ?>
    </strong></p>
    <?php
  }
  ?>
  <p class="lead">
    <?php
    printf(
      /* translators: 1: Privacy Policy guide URL, 2: Additional link attributes, 3: Accessibility text. */
      __( 'Need help putting together your new Privacy Policy page? <a href="%1$s" %2$s>Check out our guide%3$s</a> for recommendations on what content to include, along with policies suggested by your plugins and theme.' ),
      esc_url( admin_url( 'privacy-policy-guide.php' ) ),
      '',
      ''
    );
    ?>
  </p>

  <div class="row">
    <div class="col-lg-12">
        <label for="page_for_privacy_policy" class="h5">
          <?php
          if ( $this->privacy_policy_page_exists ) {
            _e( 'Change your Privacy Policy page' );
          } else {
            _e( 'Select a Privacy Policy page' );
          }
          ?>
        </label>
            <div class="row">
              <div class="col-lg-6">
              <?php
                $has_pages = (bool) get_posts(
                  array(
                    'post_type'      => 'page',
                    'posts_per_page' => 1,
                    'post_status'    => array(
                      'publish',
                      'draft',
                    ),
                  )
                );

          if ( $has_pages ) :
              ?>
          <form method="post" action="">
            <div class="row">
              <div class="col-lg-8">
                <input type="hidden" name="action" value="set-privacy-page" />
                <?php
                wp_dropdown_pages(
                  array(
                    'name' => 'page_for_privacy_policy',
                    'class' => 'form-control',
                    'show_option_none'  => __( '&mdash; Select &mdash;' ),
                    'option_none_value' => '0',
                    'selected'          => $privacy_policy_page_id,
                    'post_status'       => array( 'draft', 'publish' ),
                  )
                );

                wp_nonce_field( 'set-privacy-page' );

                ?>
              </div>
              <div class="col-lg-4">
                <?php submit_button( __( 'Use This Page' ), 'btn-outline-primary', 'submit', false, array( 'id' => 'set-page' ) ); ?>
              </div>
            </div>
          </form>
        <?php endif; ?>
              </div>
              <div class="col-lg-6">
        <form class="wp-create-privacy-page" method="post" action="">
          <input type="hidden" name="action" value="create-privacy-page" />
          <span>
          <?php
          wp_nonce_field( 'create-privacy-page' );

          submit_button( __( 'Create New Page' ), 'btn-dark', 'submit', false, array( 'id' => 'create-page' ) );
          ?>
        </form>
              </div>
            </div>
    </div>
  </div>

  <table class="form-table tools-privacy-policy-page" role="presentation">
    <tr>
      <td>

      </td>
    </tr>
  </table>
</div>