<?php $config_code_output = $this->data; ?>
<div class="wp-die-message">
  <h1 class="screen-reader-text">
    <?php _e( 'Almost done' ); ?>
  </h1>
  <p><?php printf( __( 'Unable to write to %s file.' ), '<code>configuration.php</code>' ); ?></p>
  <?php printf( __( 'You can create the %s file manually and paste the following text into it.' ), '<code>configuration.php</code>' ); ?>
  <?php echo '<textarea id="configuration" cols="98" rows="15" class="code" readonly="readonly">' . $config_code_output . '</textarea>'; ?>
  <p><?php _e( 'After you&#8217;ve done that, click &#8220;Run the installation&#8221;.' ); ?></p>
  <p class="step"><a href="<?php echo $install; ?>" class="button button-large"><?php _e( 'Run the installation' ); ?></a></p>
</div>