<div class="wp-die-message">
  
  <h1 class="screen-reader-text">
    <?php _e( 'Already Installed' ); ?>
  </h1>
  
  <p><?php echo __( 'You appear to have already installed Chartí CMS. To reinstall please clear your old database tables first.' ); ?></p>
  
  <p class="step">
    <a href="<?php echo esc_url( wp_login_url() );  ?>" class="button button-large">
      <?php echo __( 'Log In' ); ?>
    </a>
  </p>

</div>