<h1 class="screen-reader-text">
  <?php _e( 'Before getting started' ); ?>
</h1>
<p><?php _e( 'We need some information on the database. You will need to know the following items before proceeding.' ); ?></p>
<ol>
  <li><?php _e( 'Database name' ); ?></li>
  <li><?php _e( 'Database username' ); ?></li>
  <li><?php _e( 'Database password' ); ?></li>
  <li><?php _e( 'Database host' ); ?></li>
  <li><?php _e( 'Table prefix (if you want to run more than one instance in a single database)' ); ?></li>
</ol>

<p class="step"><a href="<?php echo $this->step_1; ?>" class="button button-large"><?php _e( 'Let&#8217;s go!' ); ?></a></p>