<div class="wp-die-message">
  <h1 class="screen-reader-text">
    <?php _e( 'Successfully Completed!' ); ?>
  </h1>
  <p><?php _e( '<strong>Chartí CMS</strong> has been installed!' ); ?></p>
  <p><?php _e( 'Log in to your account and let\'s create a beautiful website!') ?></p>
  <p><strong><?php _e( 'Thank you, and enjoy!' ) ?></strong></p>

  <p class="step text-center">
    <a href="<?php echo esc_url( wp_login_url() ); ?>" class="button button-large">
      <?php _e( 'Log In' ); ?>
    </a>
  </p>
</div>