<div class="wp-die-message">
  <h1 class="screen-reader-text">
    <?php _e( 'Successful Database Connection' ); ?>
  </h1>
  <p><?php _e( '<strong>All right, thirsty man!</strong> You&#8217;ve made it through this part of the installation. Database connection is ready.' ); ?></p>

  <p class="step text-center">
    <a href="install.php" class="button button-large">
      <?php _e( 'Run the installation' ); ?>
    </a>
  </p>
</div>