<?php 
    // Let CoreProtector fight with all bad monkeys out there while you drink your tea
    require_once(__DIR__  . '/../../../CoreProtector.php');
?>

<div class="wrap">
<h1>Reading Settings</h1>

  <?php settings_errors(); ?>
  <div class="row">
    <div class="col-lg-12">
    
        <div class="row">
          <div class="col-lg-6">
            <form method="post" action="options.php">
              <!-- <h3><?php _e( 'Your homepage displays' ); ?></h3> -->
              <p class="lead">Choose which page should pe set as a landing page.</p>
            <?php
              settings_fields( 'reading' );

              if ( ! in_array( get_option( 'blog_charset' ), array( 'utf8', 'utf-8', 'UTF8', 'UTF-8' ) ) ) {
                add_settings_field( 'blog_charset', __( 'Encoding for pages and feeds' ), 'options_reading_blog_charset', 'reading', 'default', array( 'label_for' => 'blog_charset' ) );
              }

              if ( ! get_pages() ) {
                echo '<input name="show_on_front" type="hidden" value="posts" />';
                if ( 'posts' != get_option( 'show_on_front' ) ) :
                  update_option( 'show_on_front', 'posts' );
                endif;

              } else {
  
                if ( 'page' === get_option( 'show_on_front' ) && ! get_option( 'page_on_front' ) && ! get_option( 'page_for_posts' ) ):
                  update_option( 'show_on_front', 'posts' );
                endif;
            ?>
              <div class="row">
                <div class="col-lg-4">
                  <label>
                    <input name="show_on_front" type="radio" value="posts" class="tog" <?php checked( 'posts', get_option( 'show_on_front' ) ); ?> />
                    <?php _e( 'Your latest posts' ); ?>
                  </label>
                </div>
                <div class="col-lg-8">
                  <label>
                      <input name="show_on_front" type="radio" value="page" class="tog" <?php checked( 'page', get_option( 'show_on_front' ) ); ?> />
                      <?php
                      printf(
                        /* translators: %s: URL to Pages screen. */
                        __( 'A <a href="%s">static page</a> (select below)' ),
                        'edit.php?post_type=page'
                      );
                      ?>
                    </label>
                  <ul>
                    <li><label for="page_on_front">
                    <?php
                    printf(
                      /* translators: %s: Select field to choose the front page. */
                      __( 'Homepage: %s' ),
                      wp_dropdown_pages(
                        array(
                          'name'              => 'page_on_front',
                          'echo'              => 0,
                          'class' => 'form-control',
                          'show_option_none'  => __( '&mdash; Select &mdash;' ),
                          'option_none_value' => '0',
                          'selected'          => get_option( 'page_on_front' ),
                        )
                      )
                    );
                    ?>
                  </label></li>

                    <li><label for="page_for_posts">
                    <?php
                    printf(
                      /* translators: %s: Select field to choose the page for posts. */
                      __( 'Posts page: %s' ),
                      wp_dropdown_pages(
                        array(
                          'name'              => 'page_for_posts',
                          'echo'              => 0,
                          'class' => 'form-control',
                          'show_option_none'  => __( '&mdash; Select &mdash;' ),
                          'option_none_value' => '0',
                          'selected'          => get_option( 'page_for_posts' ),
                        )
                      )
                    );
                    ?>
                  </label></li>
                  </ul>
                </div>
              </div>              

            <?php } ?>
            </form>
          </div>
        </div>
    </div>
  </div>


<form method="post" action="options.php">
<?php
settings_fields( 'reading' );

if ( ! in_array( get_option( 'blog_charset' ), array( 'utf8', 'utf-8', 'UTF8', 'UTF-8' ) ) ) {
  add_settings_field( 'blog_charset', __( 'Encoding for pages and feeds' ), 'options_reading_blog_charset', 'reading', 'default', array( 'label_for' => 'blog_charset' ) );
}
?>

<?php if ( ! get_pages() ) { ?>
  <input name="show_on_front" type="hidden" value="posts" />
<table class="form-table" role="presentation">
  <?php
  if ( 'posts' != get_option( 'show_on_front' ) ) :
    update_option( 'show_on_front', 'posts' );
  endif;

} else {
  if ( 'page' === get_option( 'show_on_front' ) && ! get_option( 'page_on_front' ) && ! get_option( 'page_for_posts' ) ) {
    update_option( 'show_on_front', 'posts' );
  }
  ?>
<table class="form-table" role="presentation">
<tr>
<td id="front-static-pages">

<ul>
  <li><label for="page_on_front">
  <?php
  printf(
    /* translators: %s: Select field to choose the front page. */
    __( 'Homepage: %s' ),
    wp_dropdown_pages(
      array(
        'name'              => 'page_on_front',
        'echo'              => 0,
        'show_option_none'  => __( '&mdash; Select &mdash;' ),
        'option_none_value' => '0',
        'selected'          => get_option( 'page_on_front' ),
      )
    )
  );
  ?>
</label></li>

  <li><label for="page_for_posts">
  <?php
  printf(
    /* translators: %s: Select field to choose the page for posts. */
    __( 'Posts page: %s' ),
    wp_dropdown_pages(
      array(
        'name'              => 'page_for_posts',
        'echo'              => 0,
        'show_option_none'  => __( '&mdash; Select &mdash;' ),
        'option_none_value' => '0',
        'selected'          => get_option( 'page_for_posts' ),
      )
    )
  );
  ?>
</label></li>
</ul>
  <?php if ( 'page' === get_option( 'show_on_front' ) && get_option( 'page_for_posts' ) === get_option( 'page_on_front' ) ) : ?>
  <div id="front-page-warning" class="error inline"><p><?php _e( '<strong>Warning:</strong> these pages should not be the same!' ); ?></p></div>
  <?php endif; ?>

  <?php if ( get_option( 'wp_page_for_privacy_policy' ) === get_option( 'page_for_posts' ) || get_option( 'wp_page_for_privacy_policy' ) === get_option( 'page_on_front' ) ) : ?>
  <div id="privacy-policy-page-warning" class="error inline"><p><?php _e( '<strong>Warning:</strong> these pages should not be the same as your Privacy Policy page!' ); ?></p></div>
  <?php endif; ?>

</fieldset></td>
</tr>
<?php } ?>
<tr>
<th scope="row"><label for="posts_per_page"><?php _e( 'Blog pages show at most' ); ?></label></th>
<td>
<input name="posts_per_page" type="number" step="1" min="1" id="posts_per_page" value="<?php form_option( 'posts_per_page' ); ?>" class="small-text" /> <?php _e( 'posts' ); ?>
</td>
</tr>
<tr>
<th scope="row"><label for="posts_per_rss"><?php _e( 'Syndication feeds show the most recent' ); ?></label></th>
<td><input name="posts_per_rss" type="number" step="1" min="1" id="posts_per_rss" value="<?php form_option( 'posts_per_rss' ); ?>" class="small-text" /> <?php _e( 'items' ); ?></td>
</tr>
<tr>
<th scope="row"><?php _e( 'For each post in a feed, include' ); ?> </th>
<td><fieldset><legend class="screen-reader-text"><span><?php _e( 'For each post in a feed, include' ); ?> </span></legend>
  <p>
    <label><input name="rss_use_excerpt" type="radio" value="0" <?php checked( 0, get_option( 'rss_use_excerpt' ) ); ?> /> <?php _e( 'Full text' ); ?></label><br />
    <label><input name="rss_use_excerpt" type="radio" value="1" <?php checked( 1, get_option( 'rss_use_excerpt' ) ); ?> /> <?php _e( 'Summary' ); ?></label>
  </p>
  <p class="description">
    <?php
    printf(
      /* translators: %s: Documentation URL. */
      __( 'Your theme determines how content is displayed in browsers. <a href="%s">Learn more about feeds</a>.' ),
      __( 'https://wordpress.org/support/article/wordpress-feeds/' )
    );
    ?>
  </p>
</fieldset></td>
</tr>

<tr class="option-site-visibility">
<th scope="row"><?php has_action( 'blog_privacy_selector' ) ? _e( 'Site Visibility' ) : _e( 'Search Engine Visibility' ); ?> </th>
<td><fieldset><legend class="screen-reader-text"><span><?php has_action( 'blog_privacy_selector' ) ? _e( 'Site Visibility' ) : _e( 'Search Engine Visibility' ); ?> </span></legend>
<?php if ( has_action( 'blog_privacy_selector' ) ) : ?>
  <input id="blog-public" type="radio" name="blog_public" value="1" <?php checked( '1', get_option( 'blog_public' ) ); ?> />
  <label for="blog-public"><?php _e( 'Allow search engines to index this site' ); ?></label><br/>
  <input id="blog-norobots" type="radio" name="blog_public" value="0" <?php checked( '0', get_option( 'blog_public' ) ); ?> />
  <label for="blog-norobots"><?php _e( 'Discourage search engines from indexing this site' ); ?></label>
  <p class="description"><?php _e( 'Note: Neither of these options blocks access to your site &mdash; it is up to search engines to honor your request.' ); ?></p>
  <?php
  /**
   * Enable the legacy 'Site Visibility' privacy options.
   *
   * By default the privacy options form displays a single checkbox to 'discourage' search
   * engines from indexing the site. Hooking to this action serves a dual purpose:
   * 1. Disable the single checkbox in favor of a multiple-choice list of radio buttons.
   * 2. Open the door to adding additional radio button choices to the list.
   *
   * Hooking to this action also converts the 'Search Engine Visibility' heading to the more
   * open-ended 'Site Visibility' heading.
   *
   * @since 2.1.0
   */
  do_action( 'blog_privacy_selector' );
  ?>
<?php else : ?>
  <label for="blog_public"><input name="blog_public" type="checkbox" id="blog_public" value="0" <?php checked( '0', get_option( 'blog_public' ) ); ?> />
  <?php _e( 'Discourage search engines from indexing this site' ); ?></label>
  <p class="description"><?php _e( 'It is up to search engines to honor this request.' ); ?></p>
<?php endif; ?>
</fieldset></td>
</tr>

<?php do_settings_fields( 'reading', 'default' ); ?>
</table>

<?php do_settings_sections( 'reading' ); ?>

<?php submit_button(); ?>
</form>
</div>